[tool.poetry]
name = "spyder-remote-server"
version = "0.0.1.dev0"
authors = ["Hendrik Louzada <hendriklouzada@gmail.com>"]
description = "A remote server for Spyder IDE"
readme = "README.md"
packages = [{include = "spyder_remote_server"}]

[tool.poetry.scripts]
spyder-remote-server = "spyder_remote_server.__main__:main"
configurable-http-proxy = "spyder_remote_server.configurable_http_proxy:main"
build = "pyinstaller:install"

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"
jupyterhub = "^4.0.2"
configurable-http-proxy = ">=0.3.0"
tornado = "^6.3.3"
spyder-kernels = "^3.0.0b0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.10.1"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
